__merge__: ../../api/comp_metric_regression.yaml

name: sem
namespace: "metrics"
info:
  label: SEM
  summary: Structural equation based metric
  description: |
    Uses structural equation based approach to evaluate the performance of gene regulatory network inference methods.
  metrics:
    - name: sem
      label: SEM
      summary: Captures the perfomance for the GRN in predicting gene expression data using SEM
      min: -Inf
      max: +Inf
      maximize: true
arguments:
  - name: genes_n
    type: int
    default: 5000
    info:
      label: Number of genes
      description: Number of genes to consider in the evaluation (based on most connected genes in the inferred network)

resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ tqdm_joblib==0.0.5]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]