__merge__: ../../api/comp_metric_regression.yaml

name: sem
namespace: "metrics"
info:
  label: SEM
  summary: Structural equation based metric
  description: |
    Uses structural equation based approach to evaluate the performance of gene regulatory network inference methods.
  metrics:
    - name: sem
      label: SEM
      summary: Captures the perfomance for the GRN in predicting gene expression data using SEM
      min: -Inf
      max: +Inf
      maximize: true
  
resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ lightgbm==4.3.0, numpy==1.26.4 , tqdm_joblib==0.0.5]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]