name: dictys
channels:
  - lingfeiwang
  - bioconda
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - dictys
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - mudata
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu118
    - torchvision --index-url https://download.pytorch.org/whl/cu118
    - torchaudio --index-url https://download.pytorch.org/whl/cu118