
__merge__: ../../../api/comp_method.yaml

functionality:
  name: grn_inference_scglue
  namespace: "workflows"
  info:
    label: grn_inference_scglue
    summary: "Infers GRNs from multiomics data using scglue."
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: grn_methods/scglue 

platforms:
  - type: nextflow
    directives:
      label: [twodaytime, midmem, highcpu]
