__merge__: ../../../api/comp_method.yaml


name: portia
namespace: "grn_methods"
info:
  label: portia
  summary: "GRN inference using PORTIA"
  description: |
    GRN inference using PORTIA.
  documentation_url: https://github.com/AntoinePassemiers/PORTIA


resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: continuumio/anaconda3:2024.02-1
    setup:
      - type: python
        packages: [ anndata, numpy, scipy, scikit-learn, portia-grn ]
    __merge__: ../../../api/engines/engines.yaml
  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
